### ISSUE TITLE
Update paragraph text to be consistent

### ISSUE THREAD

**Issue by moekraft** [turtlemoons/Care-On-Click#183]
**Describe the bug**
On the Carousel.html page, we use **p class="lead"** to set the font size and style. I added this to the paragraph on the About Us page. We should do the same for What we offer and How to Help

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by turtlemoons** [comment]
updated!
